# golangci-lint config - run: golangci-lint run ./...
run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosimple

linters-settings:
  goimports:
    local-prefixes: github.com/Europroiect-Estate/Codeez-AI
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
